### ISSUE TITLE
can't run plugin last version on kicad 6.0.1

### ISSUE THREAD

**Issue by Witawat** [Bouni/kicad-jlcpcb-tools#113]
![image](https://user-images.githubusercontent.com/4926369/150673843-1b2793cb-200d-493d-a6c4-906af8b3ae38.png)
![image](https://user-images.githubusercontent.com/4926369/150673880-d055099b-c34f-4af7-8660-e784a690976e.png)

**Describe the bug**
can't run plugin 

# KiCad Version
![image](https://user-images.githubusercontent.com/4926369/150673865-03ae946c-8909-42bb-aa36-01deb97bb49c.png)

**Comment by KeLaiFu** [comment]
I get the same errors on 6.0.0

**Comment by Razerban** [comment]
This issue might be related to https://github.com/Bouni/kicad-jlcpcb-tools/issues/111

**Comment by Bouni** [comment]
Indeed a duplicate of #111
