### ISSUE TITLE
Error: "Exception on python action plugin code"

### ISSUE THREAD

**Issue by LioBou** [Bouni/kicad-jlcpcb-tools#118]
**Describe the bug**
After plugin installation, first try by clicking the new icon: Error window "Exception on python action plugin code"

Text inside the error window:

**File "/home/myloginname/.local/share/kicad/6.0/3rparty/plugins/~com_github_bouni_kicad-jlcpcb-tools/plugin.py", line 20, in Run Dialog = JLCPCBTools(None)
File "/home/myloginname/.local/share/kicad/6.0/3rparty/plugins/~com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 47, in __init__self.SetSize(self.Window.FromDIP(wx.Size(1300, 800)))
AttributeError:'JLCPCBTools' object has no attribute 'FromDIP'**

**To Reproduce**
1. Installed plugin from repo as described in ReadMe
2. Running KiCAD 6.0
3. Python 3.8.10 installed
4. Running on Linux Mint 20.3 Una (base: Ubuntu 20.04 focal)

**Expected behavior**
Start the plugin, but error window, nothing else.

# KiCad Version
```
Application: KiCad PCB Editor

Version: 6.0.1-79c1e3a40b~116~ubuntu20.04.1, release build

Libraries:
	wxWidgets 3.0.4
	libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

Platform: Linux 5.4.0-96-generic x86_64, 64 bit, Little endian, wxGTK, mate, x11

Build Info:
	Date: Jan 15 2022 20:26:22
	wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.71.0
	OCC: 7.5.2
	Curl: 7.81.0
	ngspice: 31
	Compiler: GCC 9.3.0 with C++ ABI 1013

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

```

**Comment by LioBou** [comment]
I wish I can use your plugin soon, looks great!

**Comment by Bouni** [comment]
This is strange, the error message states `__init__self.SetSize(self.Window.FromDIP(wx.Size(1300, 800)))` 
`Window` is uppercase but in the code is clearly lowercase 🤔

**Comment by Bouni** [comment]
Can you verify by opening this file `/home/myloginname/.local/share/kicad/6.0/3rparty/plugins/~com_github_bouni_kicad-jlcpcb-tools/mainwindow.py` in a text editor if `Window` is lower or upper case?

**Comment by LioBou** [comment]
yes, "windows" is lower case in the code.
(I had to wrote the full error message myself as the error window do not allow selection and copy/paste, so this is me that wrongly write in upper case).

**Comment by Bouni** [comment]
OK iguess thats a `wx` issue then.
On my Windows machine I have `wxWidgets: 3.1.5 (wchar_t,wx containers)` where you have `wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24`

I need to figure out if that wx version is coming with KiCAD or if thats installed in your systems python. You maybe have to upgrade that but that might break other things on your system :worried:

**Comment by benaveld** [comment]
I got the same error on Manjaro kernal 5.15.16-1.
I tried upgraded wxWidgets to version 3.1.5. By doing that KiCad gives an error that the wrong version of wxWidgets is used.

BTW: wxWidgets: 3.0.5 is included as a dependency to KiCad.

**Comment by Bouni** [comment]
@benaveld thanks for confirming this. 

Then it must be some kind of Windows / Linux differene that I don't see at the moment ...
I'll look into it as soon as possible.

**Comment by freaf87** [comment]
Hi, 
I also got the same error in Ubuntu 20.04.3 with Kicad
Application: KiCad Version: 6.0.1-79c1e3a40b~116~ubuntu20.04.1, release build

![image](https://user-images.githubusercontent.com/5659482/151936924-30a9562e-3fea-4e1e-a37a-fdc4540120a1.png)

**Comment by Bouni** [comment]
Seems the FromDIP method was introduced in wxWidgets 3.1.0

https://docs.wxwidgets.org/trunk/classwx_window.html#aa934a31552633c076a87bca1100b0dc5

**Comment by Bouni** [comment]
@LioBou @freaf87 @benaveld 
It would be awesome if one of you guys coud test the PR befroe I merge it into main.

**Comment by LioBou** [comment]
Hi, thanks Bouni. I just tested (I basically replaced old files by the one on this branch, I'm not good yet with git), and I got a new error:
![Capture du 2022-02-03 07-43-26](https://user-images.githubusercontent.com/83333952/152293985-d172d5b6-d894-4abb-b901-5253b187a061.png)

**Comment by Bouni** [comment]
OK, GetDPIScaleFactor was intoduced even later, in 3.1.4: https://docs.wxwidgets.org/trunk/classwx_window.html#a22e9ffc6ad8aba15eecf5537f3b7791f
I'll add a workaround for that as well.

**Comment by Bouni** [comment]
@LioBou  Please test again

**Comment by LioBou** [comment]
Great, no error this time ! Seems to work ! I will try it more deeply.

**Comment by Bouni** [comment]
Nice, thank you for testing! 
I'll wait till tomorrow and then merge this.

**Comment by LioBou** [comment]
I was able to select parts and generate assembly and gerber files.
Perfect, many thanks ! I'll be able to test assembly by JLCPCB soon.

**Comment by LioBou** [comment]
@Bouni, I'd like to sponsor you and participate to your "23" goal, but when entering the amount, the "select" button is not active... Any idea what's wrong?

**Comment by Bouni** [comment]
@LioBou Highly appreaciate that you want to support me :star_struck:
I have to look into that issue, give me a few minutes

**Comment by Bouni** [comment]
@LioBou I can not see anything wrong ...
If I log out of my account in order to see the actual sponsorship page I can click the select button:

![image](https://user-images.githubusercontent.com/948965/152482017-616d0222-14e2-4307-90e8-4c6f6140d5e4.png)

Is that the select button that you cannot click?

Maybe you must add some sort of payment method to your github account, like PayPal for example!?

**Comment by LioBou** [comment]
@Bouni Yes, it is the Select button which is not active. I added payement info, still the same... :(  I have a free GitHub account, might be linked to this status ? That would be weird.

**Comment by Bouni** [comment]
I don't think so. I asked a college if he could sponsor me and for him it works. Both of us have a free account, he has no payment info configured.
What country are you from? Maybe that's the reason!?

**Comment by LioBou** [comment]
I'm from France. I thought that the dollars unit would maybe block since I'm in euros country, but most likely not that.
The thing is that the Select button is active 0,5s when I switch from monthly to one time and vice versa, and then go back grey and inactive.
I'm using Chrome, i'll try with Firefox.

4 févr. 2022 20:20:57 bouni ***@***.***>:

**Comment by LioBou** [comment]
I found the root cause... which was... Addblockplus !!
Simply deactivated for GitHub to make it work.

**Comment by Bouni** [comment]
🥳 glad you figured it out

**Comment by Bouni** [comment]
@LioBou Apparently theres no way to say Thank you through GitHub Sponsors, so I'll do it here!

Thank you @LioBou  for your support 🤩
