### ISSUE TITLE
Nice to have features for future version

### ISSUE THREAD

**Issue by bvernoux** [Bouni/kicad-jlcpcb-tools#12]
I will list nice to have features for future version of that amazing JLCPCB KiCad 5.99 (Nightly) plugin
- Add JLCPCB Plugin version(+build date) information (from github tag) in the title of the Main window "JLCPCB Tools"
  -  See https://github.com/Bouni/kicad-jlcpcb-tools/issues/15
- Main window "JLCPCB Tools" could add "LCSC Package" and "LCSC Description" from https://lcsc.com
  -  See https://github.com/Bouni/kicad-jlcpcb-tools/issues/16
- "JLCPCB Library" shall display a better Description
  - See https://github.com/Bouni/kicad-jlcpcb-tools/issues/17
- Add a way to remove LCSC reference from the JLCPCB Tools plugin (from the **part_assignments.csv** file)
  - See https://github.com/Bouni/kicad-jlcpcb-tools/issues/18
- Add a way to filter on column (for main window "JLCPCB Tools" and "JLCPCB Library")
  - See https://github.com/Bouni/kicad-jlcpcb-tools/issues/19 
- Add a way to resize windows (for main window "JLCPCB Tools" and "JLCPCB Library") 
  - See https://github.com/Bouni/kicad-jlcpcb-tools/issues/20
- Move the JLCPCB/LCSC data parsing(csv) to SQLite database to speedup search/loading ...
  - See https://github.com/Bouni/kicad-jlcpcb-tools/issues/21

**Comment by Bouni** [comment]
@bvernoux Absolutely! Feel free to open issues for each of your feature requests!

**Comment by bvernoux** [comment]
I have created one issue per item my 1st comment is updated maybe we can close this issue now ?
