### ISSUE TITLE
Plugin will not run in Kicad 6.0. Exception on python action plugin code

### ISSUE THREAD

**Issue by Tonkaman** [Bouni/kicad-jlcpcb-tools#122]
**Describe the bug**
Plug does not start.  Click button on toolbar and popup error results immediately.

**To Reproduce**
1. Click JLCPCB Tools button

**Expected behavior**
Plug in to load
![Capture](https://user-images.githubusercontent.com/74835093/152077674-ab4d186d-0b94-4163-95a6-8d91f4fd739f.JPG)

# KiCad Version

Application: KiCad PCB Editor (64-bit)

Version: (6.0.1), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19044), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jan 15 2022 13:36:27
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.5.0
	Curl: 7.78.0-DEV
	ngspice: 35
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by Bouni** [comment]
For some reason the db file was created but as an empty file 🤔 
I think I need to check for the file size, not only the existence ...
