### ISSUE TITLE
button 'Select Part' do not work

### ISSUE THREAD

**Issue by maxvid** [Bouni/kicad-jlcpcb-tools#13]
Installed the plugin today. Linux Mint. KiCad night with daily updates. The "Select part" button does not manifest itself in any way, nor does it open anything

**Comment by Bouni** [comment]
Do you see any kind of output in the Textbox in the main window that indicates an error?

**Comment by maxvid** [comment]
The field is empty.

**Comment by Bouni** [comment]
Ok, thanks for the feedback. I will have to test this out on my Arch linux machine, hopefully I can reproduce it there!

**Comment by Bouni** [comment]
I just tested this on an Arch linux machine and for me it seem that everything works as expected. The only scenario I can think of is that you didn't select any parts before clicking the select part button. At the moment the selection dialog is sapwned anyway which is not ideal, I guess I should prevent the dialog from opening if no part is selected and maybe show a warning 🤔 .

**Comment by Bouni** [comment]
@maxvid Have you tested if it still not works for you?
