### ISSUE TITLE
Edit/Copy LCSC number directly

### ISSUE THREAD

**Issue by Martinnnnnnnnnnn** [Bouni/kicad-jlcpcb-tools#131]
After selecting a part I realize: Oh, there's another identical component I missed. (Yes, I should have pressed "select alike" - maybe change that to a checkbox "always select alike before selecting part"?). It would be nice if one could copy the LCSC information directly, like copy/paste in the LCSC field in the table or double-clicking the field and entering the value manually.

**Comment by Bouni** [comment]
Maybe I should make select alike a checkbox!?
I'll see what I can do about your direct enter / copy&paste feature request

**Comment by ahalekelly** [comment]
Yes to all of these suggestions.
Another scenario it would be useful would be if you have the LCSC number already and want to just paste it in, like if you looked it up on https://yaqwsx.github.io/jlcparts/

**Comment by Bouni** [comment]
This feature was implemented by @computergeek1507 in PR #140 🥳 

![image](https://user-images.githubusercontent.com/948965/161285338-9123b101-fd84-484f-9b19-3e75d70e3394.png)
