### ISSUE TITLE
Issue with OpenSSL and KiCad 6.0 on Windows 11

### ISSUE THREAD

**Issue by krzysztofgawrys** [Bouni/kicad-jlcpcb-tools#136]
Plugin installed using Plugin and Content Manager and later manually, the same outcome.

After clicking on JLCPCB icon in PCB Editor popup window shows up:

OpenSSL: FATAL
OPENSSL_Uplink(...): no OPENSSL_Applink

Any solutions?

KiCad info:

Application: KiCad (64-bit)
Version: (6.0.1), release build
Libraries:
    wxWidgets 3.1.5
    libcurl/7.78.0-DEV Schannel zlib/1.2.11
Platform: Windows 10 (build 22000), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
    Date: Jan 15 2022 13:36:27
    wxWidgets: 3.1.5 (wchar_t,wx containers)
    Boost: 1.76.0
    OCC: 7.5.0
    Curl: 7.78.0-DEV
    ngspice: 35
    Compiler: Visual C++ 1929 without C++ ABI
Build settings:
    KICAD_USE_OCC=ON
    KICAD_SPICE=ON

**Comment by Bouni** [comment]
This seems to be ralated to the requests call to download the database 🤔 
Have you tried again since then?
Unfortunately I have no Windows 11 to test on ...

**Comment by krzysztofgawrys** [comment]
Yes i did tried again, also i found out that other plugins have the same issue, when they try to download something.
So i think this is issue in KiCad itself, not strictly limited to your plugin, therefore i will close this issue and create new one on KiCaD github.

Cheers

**Comment by Bouni** [comment]
Thanks for reporting back!
