### ISSUE TITLE
No assembly and BOM generated

### ISSUE THREAD

**Issue by thote1276** [Bouni/kicad-jlcpcb-tools#145]
HI, I test on a basic project to generate JLCPCB files. I success to have my folder in the right folder but after chossing all my component, I don't have any files in assembly.

**Comment by Bouni** [comment]
Do you get any output in the message box at the bottom when you click the generate fabrication files button?

**Comment by thote1276** [comment]
Hi,
In get output for gerber only. Non mentionof assembly as in your small video

**Comment by Bouni** [comment]
Can you share your board file so I can test it?

**Comment by thote1276** [comment]
I invite you on a repo on github, so that you can see what I get from your plugin. 
I just installed your plugin with the url, open the layout, click on the button of the plugin. 
Then I update the library, choose the component I found on JLC's library, some are missing but clicking on Make production files, i get only the gerber.

**Comment by Bouni** [comment]
I've just downloaded your repo, opend the project and started the plugin. then clicked generate fabrication files and it worked 🤔 

![grafik](https://user-images.githubusercontent.com/948965/157436950-8114bc0f-8995-42d9-896c-1ee2b8a0277b.png)

![grafik](https://user-images.githubusercontent.com/948965/157437033-144de742-b9d1-4a27-8617-da78aa83857b.png)

**Comment by thote1276** [comment]
Oh ...
Is there anything i need to download additionnal to your plugin ? Is this better to download the zip and then  paste it in the plugin folder ?

**Comment by Bouni** [comment]
Ideally you install it via PCM as explained here: https://github.com/Bouni/kicad-jlcpcb-tools#installation-

**Comment by thote1276** [comment]
I tried too.
Nothing more is needed ?
I think I add problem to export a pos file in csv. Can this be related ? A problem on my setup with csv ?

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bouni** [comment]
No, if you click the button everything should be done automatically ....

Can you post a picture of the folder structure you get with the files

**Comment by thote1276** [comment]
Hi, 
On my side i tried reinstalling Kicad and your library using PCM.

**Comment by thote1276** [comment]
I'm stuck there 
![image](https://user-images.githubusercontent.com/71173904/157550182-99f5ddbd-45d1-4a65-b37c-b21154a8d7ff.png)

**Comment by thote1276** [comment]
Maybe which Kicad are you using ? 6.0.0 ?

**Comment by Bouni** [comment]
From your screenshot I see that you're not runnig a version installed via PCM, it says [ dev ] in the bar at the top.
I run 6.0.2 and 6.99 and it works in both for me ...

Please open the console 

![image](https://user-images.githubusercontent.com/948965/157599816-c38b371b-3262-458c-9b65-78b25ef12fbe.png)

before you start the plugin, then try to generate the files again. Post the output you get in the console output window.
Maybe that helps me figuring out whats going on here.

**Comment by thote1276** [comment]
Hi, it seems to work on one of my computer with the console open. 
Today I got the error, database is locked on the first computer.

**Comment by thote1276** [comment]
Hi, 
I think the final word was that the antivirus software was blocking one of your script I think !
