### ISSUE TITLE
BOM file does not update LCSC partnumber from the board

### ISSUE THREAD

**Issue by lpdx** [Bouni/kicad-jlcpcb-tools#154]
**Describe the bug**
After change a LCSC Part from a component in schematic and update board from schematics the old part number remains. It does not update.

**To Reproduce**
1. Create new project
2. Add a component
3. Edit the LSCS part number
4. Anotate and generate  a board
5. Run JLCPCB tools [2022.04.02]
6. Click in "Generate fabrication file"
7. Change LSCS part number (due the component shortage, for example)
8.![1](https://user-images.githubusercontent.com/13546280/161617809-110ad203-c0fa-429c-9e0b-541c4f5f7581.png)
9. Update board from schematic
10. Run  JLCPCB tools [2022.04.02]
11. The old partnumber is presented and a message in the log box is presented: "2022.04.04 16:15:08 - DEBUG - update_from_board -  Part C101 is already in the database and has a lcsc value, the value supplied from the board will be ignored."

![2](https://user-images.githubusercontent.com/13546280/161617814-cfd3b4e6-39d4-42cc-84ae-8cafa591d320.png)

**Expected behavior**
If we change a part number it means that we need to change the component and this data must be reflected in the BOM in order to buy the correct item. Deleting the file "project.db" by hand to generate a correct BOM is error prone.

# KiCad Version
```
Application: KiCad (64-bit)


Version: (6.0.1), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 22000), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jan 15 2022 13:36:27
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.5.0
	Curl: 7.78.0-DEV
	ngspice: 35
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by Bouni** [comment]
This was by intention!

Currently there's no way of writing selected LCSC numbers back to the schematic. If you have a LCSC number in the schematic and decide within the plugin to assign another LCSC number you can do that and it will not be overwritten from the schematic when you open the plugin again.

If you want to achive what you describe, you can simply use the remove part button on that component and the LCSC number from the schmatic will be asigne when you next time load the plugin.

Let me know if that is enough explanation.

**Comment by Bouni** [comment]
> Indeed it might be nice if there was a configuration option to "always recreate the database".

I'm still in the process of figuring out a way of let the user configure his settings so maybe I will include your case as well
