### ISSUE TITLE
Part Details dialog can't get input focus

### ISSUE THREAD

**Issue by alibenpeng** [Bouni/kicad-jlcpcb-tools#165]
**Describe the bug**
The "Part Details" dialog opens but never gets the input focus until the parent ("Select Part"/"JLCPCB Library", in my case) window is closed.

**To Reproduce**
1. Open JLCPCB Tools via toolbar button
2. Select a part from the list
3. Click on "Select Part"
4. Find and select a part in "JLCPCB Library" window
5. Click on "Part Details"
6. The window opens but doesn't get focus, and can't even be closed again as long as the parent window is open. Also, typing Ctrl-W will close the parent window instead of the details dialog, which is quite annoying.

**Expected behavior**
The "Part Details" dialog should behave like any regular window.

# KiCad Version

```
Version: 6.0.4-6f826c9f35~116~ubuntu20.04.1, release build
```

**Comment by livigni** [comment]
same issue here

**Comment by Bouni** [comment]
I'll take a look at this as soon as possible ..

**Comment by ayourk** [comment]
As an aside to this, only when I close the "JLCPCB Library" window can I then click on the "Open Datasheet" button in the "JLPCB Part Details" window.  Also, While the "JLCPCB Library" window is open, I cannot close any "JLPCB Part Details" windows until the "JLCPCB Library" window is closed.  Maybe the parent window is becoming modal or something like that?

**Comment by Bouni** [comment]
@ayourk 🤔 maybe thats part off this issue. I need to look into this but first have to setup a linux machine including desktop which takes some time. Maybe I invest some more time and create a vm that I cna use for testing in the future ...

**Comment by Bouni** [comment]
I finally can reproduce it in a Ubuntu VM. The strange thig is that if the part details windo is opend from the main window, everything works as expected, but if I start it from the select part window the behaviour is as you've described it ....

**Comment by Bouni** [comment]
I tried now various things but its still a mystery to me whats going on here 😞 
Maybe I'm able to figure it out in the log run but at the moment I have not the slightes idea what else to try ....

**Comment by livigni** [comment]
I have to say that I get same behaviour on macOs, so it shouldn't be a linux only thing. 
The thing is happening when I'm searching for a component and then I select one option and click on part details. Then it is not possible to get focus on that window, as it appears below the Search one. 
I believe that somehow the window got opened thinking it was called by the main Table view...

 
I explained myself terribly so I hope you could get some of what I meant :) Unfortunately I cannot send some screencast now as I am without external display and the plugin icon cannot be clicked (I think I will open another bug on this).

**Comment by ayourk** [comment]
MacOS is a Unix based OS these days, so not sure how "Windows" related it is.

**Comment by Bouni** [comment]
This is solved in the latest release.
