### ISSUE TITLE
"JLCPCB Library" shall display a better Description

### ISSUE THREAD

**Issue by bvernoux** [Bouni/kicad-jlcpcb-tools#17]
In "JLCPCB Library" display add the Description from https://github.com/yaqwsx/jlcparts/blob/master/LCSC-API.md (instead of the ones from https://jlcpcb.com/parts) as the one from https://jlcpcb.com/parts is unreadable and not accurate
- Maybe first step will be to "parse/extract/display" correctly the "LCSC Description" from the csv as it is not displayed correctly today.
- Example screenshot with issue (°C ... not displayed correctly ...) on Description
![image](https://user-images.githubusercontent.com/432709/131330435-44abfef9-9754-4f91-83c9-8fcfbb22d853.png)
![image](https://user-images.githubusercontent.com/432709/131330576-323e73c3-4d53-4d95-a3e5-6ee203cbe42c.png)

**Comment by Bouni** [comment]
I fixed "incorrect description" with https://github.com/Bouni/kicad-jlcpcb-tools/commit/0ce0c3d77250125afff72d7118a4019c41b81ee9
The encoding of the CSV is `gbk` rather than `iso-8859-1`

**Comment by Bouni** [comment]
As this is kind of the same issue / enhancement as #16 I'll go to work out a solution over there and use it in bth, the main window and the library.

**Comment by bvernoux** [comment]
I confirm all work fine with Windows10 + KiCad Nightly (r24220)
