### ISSUE TITLE
Error unexpected type 'Bitmap' with KiCad 6.0.6 Windows10 64bits

### ISSUE THREAD

**Issue by bvernoux** [Bouni/kicad-jlcpcb-tools#179]
**Describe the bug**
When lauching kicad-jlcpcb-tools an error windows appears
![image](https://user-images.githubusercontent.com/432709/174583259-c6ca17c4-f1e2-4d73-b081-54894f4b4705.png)
Tested with latest version 48cd6d141ad54c7e38ec68fcd851785db8d5b134

**To Reproduce**
1. Go to 'PCB Editor'
2. Click on 'kicad-jlcpcb-tools' icon

![image](https://user-images.githubusercontent.com/432709/174583259-c6ca17c4-f1e2-4d73-b081-54894f4b4705.png)

**Expected behavior**
The plugin shall work like on previous version KiCad 6.0.5

# KiCad Version
```
Application: KiCad PCB Editor (64-bit)

Version: (6.0.6), release build

Libraries:
	wxWidgets 3.1.6
	libcurl/7.82.0-DEV Schannel zlib/1.2.12

Platform: Windows 10 (build 19044), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jun 18 2022 23:26:20
	wxWidgets: 3.1.6 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.0
	Curl: 7.82.0-DEV
	ngspice: 37
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by Bouni** [comment]
@bvernoux Please test the referenced PR, that should fix your issue.

**Comment by bvernoux** [comment]
I confirm https://github.com/Bouni/kicad-jlcpcb-tools/pull/180 solve the issue on KiCad 6.0.6

**Comment by Bouni** [comment]
Nice, thanks for your feedback!
