### ISSUE TITLE
Add a way to remove LCSC reference from the JLCPCB Tools plugin (from the part_assignments.csv file) 

### ISSUE THREAD

**Issue by bvernoux** [Bouni/kicad-jlcpcb-tools#18]
Add a way to remove LCSC reference from the JLCPCB Tools plugin (from the part_assignments.csv file)
- In some case it is possible the part_assignments.csv is obsolete and some LCSC reference are wrong and have no replacement (and does not exist in schematic) so today there is no easy way to remove those LCSC reference (except by editing the part_assignments.csv file by hand ...)

**Comment by Bouni** [comment]
Done by https://github.com/Bouni/kicad-jlcpcb-tools/commit/93317bfe918a1d6117e2989f03f7561415605edf

**Comment by Bouni** [comment]
@bvernoux Please be so kind and test this feature

**Comment by bvernoux** [comment]
The "Remove part" feature work perfectly tested with Windows 10 and KiCad 5.99 Nightly (kicad-r23938)
Perfect job like always !!
