### ISSUE TITLE
Add a way to filter on column (for main window "JLCPCB Tools" and "JLCPCB Library")

### ISSUE THREAD

**Issue by bvernoux** [Bouni/kicad-jlcpcb-tools#19]
Add a way to filter on column (for main window "JLCPCB Tools" and "JLCPCB Library")
- Just a simple filter (Sort Ascending/Descending) on one column at a time if possible with "natural sort" (like we have in LibreOffice Calc => Menu Data => Sort... => Options => Enable natural sort)

**Comment by Bouni** [comment]
wx allow to make columns sortable, which I added with the latest commit. Not sure if it sorts the way you want it to but I'm statisfied 😉 
@bvernoux please check if this fit your needs

**Comment by bvernoux** [comment]
I confirm the column sort work fine (even if it does not use "natural sort" which means for example when you have C1 to C9 then C10 the natural sort will sort it like that in your case with standard sort it does C10, C1, C2 ....) which is not very convenient but ok

**Comment by Bouni** [comment]
I think I could implement a custom sorting function and call it on click to the header. 
But to be honest, thats a lot of work for a minor improvement.
Maybe I go for that in the future and leave it as it is for now.
I hope you can live with that 😅
