### ISSUE TITLE
Component offset in POS file

### ISSUE THREAD

**Issue by tmckzs** [Bouni/kicad-jlcpcb-tools#194]
Hi,
To be fair, I am not sure if it is some configuration I have, or something to do with the plugin..

**Describe the bug**
Position data is offset for components selected through the JLCPCB component selector. ~7.6mm in -x direction

**To Reproduce**
1. Go to PCBNEW
2. Click plugin button
3. Select JLCPCB Components
4. Generate assembly files
5. View POS file is incorrect (Within JLCPCB viewer) -> components are shifted 7.61118mm -x

**Expected behavior**
POS file to be correct

# KiCad Version
```
Application: KiCad (64-bit)

Version: (6.0.6), release build

Libraries:
	wxWidgets 3.1.6
	libcurl/7.82.0-DEV Schannel zlib/1.2.12

Platform: Windows 11 (build 22000), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jun 26 2022 02:39:06
	wxWidgets: 3.1.6 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.0
	Curl: 7.82.0-DEV
	ngspice: 37
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

```

**Comment by Bouni** [comment]
7.6mm sounds dangerously close to 7.62mm which is 300mil, might be a inch/metric setting in KiCAD 🤔 
Can you share the project that makes the problem?

**Comment by tmckzs** [comment]
Yes, I will send it to you.

v/r
Tharon Stewart
719-964-8534

**Comment by tmckzs** [comment]
Interesting, for me it offsets R1..R4 -x ~7.62mm.

Version is 2022.01.01

I suppose one of my local settings must be conflicting... thank you for your investigation - will try resetting KiCad settings, etc.

**Comment by Jan21493** [comment]
I have a similar problem, maybe it's related to the "origin point" that I had set to the upper left corner of the pcb (recommendation from a youtube video to find the position on the board easier). The gerber file looks to be O.K., also the viewer at JLCPCB had correct placements. Only the assembly of parts has reported an error:

![Produce_DanZhi SMT_Original_Snapshot Top 3578953A_Y2 SMT0220726917126](https://user-images.githubusercontent.com/25911411/181204383-163454da-2229-4cb0-8b6d-3bcedc8d986b.png)

The offset is exactly the distance from the upper left corner of the page to the corner in the pcb. In the POS file the coordinates for "Mid X,Mid Y" looks to always start from the page, but not the origin point. 

I'm quite new to KiCad, so this might be an error on my side.

**Comment by Jan21493** [comment]
I was a bit impatient, so I modified the plugin a bit. I replaced a part in file fabrication.py:
```
    def generate_pos(self):
        """Generate placement file (POS)."""
        posname = f"POS-{self.filename.split('.')[0]}.csv"
        self.corrections = self.parent.library.get_all_correction_data()
        designSettings = self.board.GetDesignSettings()
        m_place_Offset = designSettings.GetAuxOrigin()
        self.logger.info(f"origin point for POS data is origin point for drill files (%d, %d) mm" % (ToMM(m_place_Offset.x),ToMM(m_place_Offset.y)))
        with open(
            os.path.join(self.assemblydir, posname), "w", newline="", encoding="utf-8"
        ) as csvfile:
            writer = csv.writer(csvfile, delimiter=",")
            writer.writerow(
                ["Designator", "Val", "Package", "Mid X", "Mid Y", "Rotation", "Layer"]
            )
            for part in self.parent.store.read_pos_parts():
                for fp in get_footprint_by_ref(self.board, part[0]):
                    if get_exclude_from_pos(fp):
                        continue
                    fp_pos  = fp.GetPosition()
                    fp_pos -= m_place_Offset
                    writer.writerow(
                        [
                            part[0],
                            part[1],
                            part[2],
                            ToMM(fp_pos.x),
                            ToMM(fp_pos.y) * -1,
                            self.fix_rotation(fp),
                            "top" if fp.GetLayer() == 0 else "bottom",
                        ]
                    )
        self.logger.info(f"Finished generating POS file")
```

It should be easy to find. It looks that this solves the problem for myself. I haven't ordered a new pcb yet and I've only verified the top layer, so I'm not sure if this solves the problem completely.

**Comment by Bouni** [comment]
@Jan21493 very good finding! Would you mind testing my PR before I merge it?

**Comment by Jan21493** [comment]
I still have problem with the POS aka Component Placement List (CPL) file as JLCPCB calls it. Yesterday I've ordered an updated pcb with smd assembly and the positions in the POS file with my quick fix were exactly the same as with code change #199 (your fix is more elegant to be honest). 

I'm quite new to KiCad as well as ordering via JLCPCB. Now I'm really confused. For the second order I've moved the left corner of the pcb to 20/20 mm from the origin of the page and I got the same placement error as shown above. I've repeated all steps with files from my first and second order a couple of times. Here are the results:

- if gerber files and POS file are using the upper left corner from the page as origin points (that is the case without #199), then the JLCPCB online viewer for assembly shows the correct placement:
<img width="1457" alt="JLCPCB online viewer for assembly" src="https://user-images.githubusercontent.com/25911411/181636759-e75c61e1-31fb-42c8-9a99-d02150bee059.png">

- if gerber files is using upper left corner of the page, but POS file the auxOrigin (that is moved e.g. to upper left corner of the pcb) and fix #199 is applied, then the result is a WRONG placement. Here's a screenshot of my second version:
<img width="1462" alt="JLCPCB online viewer for assembly with auxOrigin" src="https://user-images.githubusercontent.com/25911411/181638002-b8ae3c2b-ce83-4bf1-aabc-dbb9476d2c8e.png">

So fix #199 does not work - so far. I had another look into the **_fabrication.py_** file and the "inspired by ..." link. There I found the missing command: `popt.SetUseAuxOrigin(True)` That needs to be added to the "# gerber section", e.g. at the end at line 126. The result is:
<img width="1460" alt="JLCPCB online viewer for assembly with auxOrigin and additional fix for gerber" src="https://user-images.githubusercontent.com/25911411/181642266-ccce3213-bd55-4052-b2be-d518d849207f.png">

Now it looks good again. I have no idea, why I got that error in "DFM Analysis" with my first order:
<img width="887" alt="JLCPCB DFM analysis" src="https://user-images.githubusercontent.com/25911411/181642857-e6b0b5e3-d4ac-4874-9e43-0b055ea303c2.png">

Maybe that's normal when the option "_Confirm Parts Placement_" is set to "_yes_"? However that would be really confusing for new customers. 

Well with that testing and knowledge from above I'm not sure if it was worth to spend the effort to create #199 to use the auxOrigin, but as 90% of the code is already done, I would agree to add the missing command as well. If somebody does not change the **auxOrigin**, then it should be as without that fix #199. If _auxOrigin_ is changed, then it's used for production. According to the tooltip help in KiCAD for this feature: "_Place origin point for drill files and component placement files_" it was meant for this.

**Comment by Bouni** [comment]
Thank you for your detailed research!
I guess when we use the PR #199 and add `popt.SetUseAuxOrigin(True)` as well we cover most cases.

**Comment by Bouni** [comment]
It as I expected, if we take the AuxOrigin into account in the POS file as well as the Gerbers, we're good to go

AuxOrigin set like this 

![image](https://user-images.githubusercontent.com/948965/181685104-498cccc7-4118-4a90-8af6-c3b2d6e7927c.png)


AuxOrigin only in POS generation results in:
![image](https://user-images.githubusercontent.com/948965/181685080-3e88d145-9042-4cb5-b6b0-c3e4f6cda737.png)

And with the `popt.SetUseAuxOrigin(True)` option

![image](https://user-images.githubusercontent.com/948965/181685178-70bfc1e5-d873-46ce-a163-036c51d80fcd.png)

**Comment by Jan21493** [comment]
Welcome. Thank you for the plugin! Yes, that's also my opinion.

**Comment by dzid26** [comment]
Is AuxOrign position causing the offset? 
<img width="807" alt="image" src="https://github.com/Bouni/kicad-jlcpcb-tools/assets/841061/4e49a627-c1fc-4fc0-b563-cb90952702fd">
 Where should it placed for irregular board shape?
