### ISSUE TITLE
Add a way to resize windows (for main window "JLCPCB Tools" and "JLCPCB Library")

### ISSUE THREAD

**Issue by bvernoux** [Bouni/kicad-jlcpcb-tools#20]

**Comment by Bouni** [comment]
Fixed by https://github.com/Bouni/kicad-jlcpcb-tools/commit/1143085f76723d29d843ab0fda27fc10fb5a1212

**Comment by Bouni** [comment]
@bvernoux Please be so kind and test this feature

**Comment by bvernoux** [comment]
The resize work perfectly tested with Windows 10 in both main window "JLCPCB Tools" and "JLCPCB Library"
Perfect job like always !!

**Comment by Bouni** [comment]
Thanks for the feedback 😄
