### ISSUE TITLE
LCSC field in schematic updated incorrectly

### ISSUE THREAD

**Issue by silicongarage** [Bouni/kicad-jlcpcb-tools#210]
When clicking 'Export to Schematic' the plugin will incorrectly update the LCSC field of objects in the schematic.
Depending if all schematic objects have an LCSC field or not two different behaviors occur.   
(A) All objects have LCSC field:  The plugin fails to update the schematic objects LCSC fields with values from plugin database.
(B) At least one object doesn't have LCSC field: The plugin updates numerous schematic objects with the same value from (what appears to be) the first item in the plugin database.  It also will create a second LCSC field on some of the schematic objects.

**To Reproduce**
1. Click on 'Export to Schematics'

**Expected behavior**
Schematic updated with a single LCSC field containing value from plugin database.

# Plugin Version
2022.08.01

# KiCad Version

```
Application: KiCad PCB Editor

Version: (6.0.7-1)-1, release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.64.1 SecureTransport (LibreSSL/2.8.3) zlib/1.2.11 nghttp2/1.41.0

Platform: macOS Big Sur Version 11.6.8 (Build 20G730), 64 bit, Little endian, wxMac

Build Info:
	Date: Jul 26 2022 20:28:16
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.2
	Curl: 7.64.1
	ngspice: 35
	Compiler: Clang 12.0.0 with C++ ABI 1002

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by computergeek1507** [comment]
I was using this the yesterday and it is not working correctly, I will try to fix it.
