### ISSUE TITLE
Tinted via suddenly deactivated

### ISSUE THREAD

**Issue by glowingkitty** [Bouni/kicad-jlcpcb-tools#219]
I recently reset my computer and also reinstalled KiCad and the JLCPCB plugin. And suddenly the jlcpcb tools plugin exports the gerber files without tinted vias. Just double checked - when I export from KiCad with the default settings, the vias are tinted (which I also wanted to have).
Did you change the default export settings for your plugin? and how can one overwrite them?

**Comment by Bouni** [comment]
What version do you run?
I recently set that back to tented by default which is inluded in the [latest version 2022.09.01](https://github.com/Bouni/kicad-jlcpcb-tools/blob/5c25592e47f8682dbe2c45d0d3fa5b8da4e3c253/fabrication.py#L114)

**Comment by zaxour** [comment]
Tented vias are back! Thank you for fixing this!

**Comment by Bouni** [comment]
So that means that @glowingkitty is using a older version then.
Please update to solve your issue!
