### ISSUE TITLE
BOM isn´t generated and CPL is empty

### ISSUE THREAD

**Issue by radontec** [Bouni/kicad-jlcpcb-tools#22]
unfortunately, no CPLs are generated. the BOM is also missing. I suspect that the fault lies with the solder bridges. I can not unselect these from the BOM and the CPL.
![2021-08-31 11_15_09-assembly](https://user-images.githubusercontent.com/58628249/131477336-1d59f4d1-f285-4b66-8c7d-f2fc67ca619a.jpg)
![2021-08-31 11_14_06-rund — Leiterplatteneditor](https://user-images.githubusercontent.com/58628249/131477339-28d3b687-552e-4cbf-8dc6-59e7257fbc8d.jpg)

it´s not possible to switch from yes to no
![grafik](https://user-images.githubusercontent.com/58628249/131477579-7fa107c8-3e6d-41b1-8e2d-cc1118cbf862.png)

**Comment by Bouni** [comment]
Do you get any error message when clicking the Generate fabrication files button?
I can confirm that it is not possible to toggle the CPL / BOM state for footprints that have just a `REF**` as Reference designator because I look them up by the reference and here its multiple that share the same reference.
I need to look for away to solve this.

**Comment by radontec** [comment]
no error message:

2021.08.31 12:19:59 - INFO - Load corrections from https://raw.githubusercontent.com/matthewlai/JLCKicadTools/master/jlc_kicad_tools/cpl_rotations_db.csv
2021.08.31 12:19:59 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2021.08.31 12:20:00 - DEBUG - https://raw.githubusercontent.com:443 "GET /matthewlai/JLCKicadTools/master/jlc_kicad_tools/cpl_rotations_db.csv HTTP/1.1" 200 553
2021.08.31 12:20:02 - INFO - Loaded Library with 227970 parts
2021.08.31 12:20:05 - INFO - Successfully ploted Top layer
2021.08.31 12:20:05 - INFO - Successfully ploted Silk top
2021.08.31 12:20:05 - INFO - Successfully ploted Mask top
2021.08.31 12:20:05 - INFO - Successfully ploted Bottom layer
2021.08.31 12:20:05 - INFO - Successfully ploted Silk top
2021.08.31 12:20:05 - INFO - Successfully ploted Mask bottom
2021.08.31 12:20:05 - INFO - Successfully ploted Edges
2021.08.31 12:20:05 - INFO - Finished generating Excellon files
2021.08.31 12:20:05 - INFO - Finished generating ZIP file

**Comment by Bouni** [comment]
I thought a bit about this issue and I will simply ignore footprints that have no reference (REF**).
Its very simple to implement and those are invalid for production anyway.

**Comment by Bouni** [comment]
@radontec Would you please test my latest commit? 
Works for me:

![image](https://user-images.githubusercontent.com/948965/131502758-b6528147-0e1b-4320-b016-b4316388e269.png)

**Comment by radontec** [comment]
got a new exception
![grafik](https://user-images.githubusercontent.com/58628249/131539596-e45dc19f-17c4-4c38-82cb-301e5afd8c25.png)

**Comment by Bouni** [comment]
@radontec Fixed this issue in the last commit, would you mind trying again?

**Comment by radontec** [comment]
now it works perfect! love this plugin
