### ISSUE TITLE
Part curve and stretch incorrect

### ISSUE THREAD

**Issue by missikos** [Bouni/kicad-jlcpcb-tools#222]
**Describe the bug**
Importing KEYSTONE 1056 ([C238067](https://lcsc.com/product-detail/Battery-Connectors_span-style-background-color-ff0-Keystone-span-1056_C238067.html))
The curve of the bottom left appears incorrect. Additionally, the footprint is squished horizontally ie with doesn't appear correct.

**To Reproduce**
1. Import C238067
2. Inspect curve and width
3. Compare to EasyEDA version (images attached)

**Expected behavior**
Replicate EasyEDA footprint

# KiCad Version
6.0.2-0

Images:
![Screen Shot 2022-09-16 at 11 29 42 am](https://user-images.githubusercontent.com/59293/190537271-28339fd2-dfbe-410e-92d3-5785e4ea5a13.png)
![Screen Shot 2022-09-16 at 11 23 10 am](https://user-images.githubusercontent.com/59293/190537277-5a46126b-0d8c-4a95-816f-b57e4543f67e.png)

Thank you

**Comment by Bouni** [comment]
I guess you opened this issue in the wrong repo, kicad-jlcpcb-tools does not create symbols and footprints.
You might got these from https://github.com/uPesy/easyeda2kicad.py
