### ISSUE TITLE
commit causes endless recursion

### ISSUE THREAD

**Issue by klvnptr** [Bouni/kicad-jlcpcb-tools#224]
Hello,

This commit: https://github.com/Bouni/kicad-jlcpcb-tools/commit/84233065352aeb74e82025baeaddb7999a5b9990
causes infinite loop when clicking on "Generate fabrication". The ZIP file gets bigger and bigger, Kicad hangs, and has to be shut down from Activity Monitor (MacOS).

Checking out the previous commit works flawlessly.

Thanks
Peter

**Comment by eric-wood** [comment]
I've been experiencing the same issue after pulling down the latest version (KiCad 6.0.7-1, MacOS 12.5.1)

**Comment by Bouni** [comment]
Strange, this seems to happen only in 6.0.7 but not in 6.99 🤔

**Comment by Bouni** [comment]
I've reverted the latest commit, that should fix this issue ...
