### ISSUE TITLE
Export to schematic creates wrong linebreak pasting LCSC part numbers from excel

### ISSUE THREAD

**Issue by timhellwig** [Bouni/kicad-jlcpcb-tools#230]
![image](https://user-images.githubusercontent.com/28982596/195512983-85ddf194-2cb0-4321-9148-a87ba88fa7ba.png)
![image](https://user-images.githubusercontent.com/28982596/195513059-01ca1a9c-ca1b-4fd9-9848-15207bac07b9.png)

Part numbers were inserted into mapping via ricght click and paste LCSC by copying the part number out of excel.

**Comment by Bouni** [comment]
This looks to as if there was a newline after the LCSC number pasted into the field.

We probably should sanitize the input.

@computergeek1507 I think you've added this feature, maybe you could have a look 😅

**Comment by Bouni** [comment]
Fixed in #231
