### ISSUE TITLE
Problem repository link

### ISSUE THREAD

**Issue by okhanvatansever** [Bouni/kicad-jlcpcb-tools#251]
**Describe the bug**
Problem installing Kicad PCM. Error with repository link: "Failure when recieving data from the peer" "could not read repository url".

**To Reproduce**
1. Go to Plugin and content manager and add new repository link.
2. See error

**Expected behavior**
Normally I would have added the repository so I could install the addon,

# KiCad Version
6.0.10

**Comment by Bouni** [comment]
@okhanvatansever I've just upgraded from 6.0.9 to 6.0.10 and suddenly I have the same issue:

![grafik](https://user-images.githubusercontent.com/948965/209928967-7a04ca73-46ac-49a8-a06d-a85c18311be9.png)

I guess this is some KiCAD issue. Let me check if there are open issues on KiCad's Gitlab.

**Comment by Bouni** [comment]
I filed a new issue on KiCADs GitLab: https://gitlab.com/kicad/code/kicad/-/issues/13307

**Comment by Bouni** [comment]
Fixed in Kicad `6.0.11` and `7.0.0-rc2-62-g971abcfc1a`
