### ISSUE TITLE
Double sided placement for JLCPCB Standard

### ISSUE THREAD

**Issue by ccdkid** [Bouni/kicad-jlcpcb-tools#268]
Is there a chance to make it possible?

**Comment by Bouni** [comment]
What exactly does not work / is missing for it to work?

I've never used the Standard service so far ...

**Comment by Bouni** [comment]
I Just did a quick test and it seems that this as already working fine!

![grafik](https://user-images.githubusercontent.com/948965/213443303-8db21034-7b8b-440d-9656-15115bd20c0f.png)

**Comment by ccdkid** [comment]
Sorry, my fault. It works like a charme. Looking forward for the new API. Great work, keep on going 👍

**Comment by bvernoux** [comment]
> I Just did a quick test and it seems that this as already working fine!
> 
> This 3D view is out of the JLCPCB board viewer: ![grafik](https://user-images.githubusercontent.com/948965/213443303-8db21034-7b8b-440d-9656-15115bd20c0f.png)

I confirm I have used with success kicad-jlcpcb-tools (latest version I update it regularly) plugins with KiCad 6.0.10 with JLCPCB with Double Side placement on several boards
