### ISSUE TITLE
Tented vias through plugin settings on Mac has inverse behaviour 

### ISSUE THREAD

**Issue by rlake** [Bouni/kicad-jlcpcb-tools#275]
tools version 2023.01.02

If I generate gerbers with the box checked "Tented vias" the output files have untented vias. With the box unchecked (now showing "Untented vias" and corresponding graphic) the output files contain tented vias.

I'd expect the opposite, i.e. following the text shown alongside the checkbox to be the actual behaviour.

# KiCad Version
```
Application: KiCad PCB Editor

Version: (6.0.10-0), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.86.0 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.47.0

Platform: macOS Version 13.2 (Build 22D49), 64 bit, Little endian, wxMac

Build Info:
	Date: Dec 18 2022 11:46:04
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.80.0
	OCC: 7.6.3
	Curl: 7.64.1
	ngspice: 38
	Compiler: Clang 12.0.0 with C++ ABI 1002

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by Bouni** [comment]
You're absolutely right :expressionless:, I'll release a fixed version today
