### ISSUE TITLE
Options to plot "Reference Designators" and "Footprint Values" on the Silkscreen

### ISSUE THREAD

**Issue by julian-w** [Bouni/kicad-jlcpcb-tools#281]
**Is your feature request related to a problem? Please describe.**
Normally I do not print the reference designators in the silkscreen when I let JLCPCB assemble the whole PCB. However, when the production data is created automatically, they are also included. Therefore, I always have to create and replace the silkscreen manually. However, as soon as I create and replace the silkscreen manually, for reasons unknown to me the preview in JLCPCB no longer works correctly, which makes it difficult to work with the files.

**Describe the solution you'd like**
In the settings menu, an option to switch off plotting the "Reference Designators" (and maybe the same for "Footprint Values").

**Describe alternatives you've considered**
I don't see any real alternative to always doing it by hand.

**Additional context**
When the complete board is assembled, a Silkscreen without Reference Designators is much nicer and you don't have to move them manually to make it fit.

**Comment by Bouni** [comment]
Can you test if setting these two values to `False` gives you the desired output?

https://github.com/Bouni/kicad-jlcpcb-tools/blob/main/fabrication.py#L118-L119

I fthat dows the job I'll add settings for them so users can decide if the want Reference Designators and/or Footprint Values or not.
