### ISSUE TITLE
Error: The wx.App object must be created first in Stock Ubuntu 22.04 KiCAD

### ISSUE THREAD

**Issue by hansfbaier** [Bouni/kicad-jlcpcb-tools#291]
The issue and the fix is described in detail here:
https://techoverflow.net/2023/03/01/how-to-fix-kicad-jlcpcb-fabrication-plugin-error-the-wx-app-object-must-be-created-first/

**Comment by hansfbaier** [comment]
Seems to be the KiCAD version:
https://forum.kicad.info/t/cant-run-any-installed-plugin-after-update-wx-error/38028
So not a fault of this project.

**Comment by hansfbaier** [comment]
The issues persists even after updating to the latest version of KiCAD 6 from the KiCAD ppa.

**Comment by hansfbaier** [comment]
![image](https://user-images.githubusercontent.com/148607/222351368-bd466953-6fec-4f58-8e50-41313a55967d.png)

**Comment by hansfbaier** [comment]
The fix from the first links works:
```diff
--- a/mainwindow.py
+++ b/mainwindow.py
@@ -64,6 +64,7 @@ ID_CONTEXT_MENU_ADD_ROT_BY_NAME = wx.NewIdRef()
 
 class JLCPCBTools(wx.Dialog):
     def __init__(self, parent):
+        self.app = wx.PySimpleApp()
         wx.Dialog.__init__(
             self,
             parent,
```

**Comment by Bouni** [comment]
I need to make sure that this works on all platforms and not just on Ubuntu. If that's not the case we need to bring some sort of OS detection on place in order to get it working on all platforms ...
I guess its just another type of "wrong" wx version in place. wx is a nightmare 😞

**Comment by Bouni** [comment]
I've tested your suggestion on Windows 11 and it seems to work.
I'll add this into the next release and hope it doesn't break anything on other platforms ...

**Comment by hansfbaier** [comment]
Great, thanks!
