### ISSUE TITLE
Plugin does no longer work on OSX with KiCAD 7.0

### ISSUE THREAD

**Issue by Bouni** [Bouni/kicad-jlcpcb-tools#295]
**Describe the bug**
The plugin does not start at all.

**To Reproduce**
Install the latest version on OSX + KiCAD 7.0

**Expected behavior**
The plugin should start

# KiCad Version

```
7.0
```

**Comment by Bouni** [comment]
This was reported to me on other channels and I'll put that here for documentation.

**Comment by Bouni** [comment]
It seems that #292 makes the plugin fail on OSX. After the user commented  https://github.com/Bouni/kicad-jlcpcb-tools/blob/main/mainwindow.py#L67 it works again.

**Comment by badrbouslikhin** [comment]
> @hansfbaier You reported this in #291, can you please test if changing the line 67 in mainwindow.py to `self.app = wx.App()` works for you as well?

I am running into the same issue.
Changing the line 67 in mainwindow.py to `self.app = wx.App()` doesn't fix the issue. There's no output in the Python console but no JLCPCB Tools window does not appear.
Commenting line 67 fixes the issue though.

**Comment by hansfbaier** [comment]
@Bouni Yes, replacing that works for me as well.

**Comment by octave** [comment]
I have to comment line 67 of `mainwindow.py` as well to make it work with `Kicad 7.0.1` on `macOS 13.2.1`.

**Comment by shuki25** [comment]
> I have to comment line 67 of `mainwindow.py` as well to make it work with `Kicad 7.0.1` on `macOS 13.2.1`.

I confirm that this fix works for me on Kicad 7.0 on MacOS Ventura (13.2.1) on Apple Silicon (M2).

**Comment by JohnVidler** [comment]
I also confirm that commenting line 67 on my M1-max Mac running Ventura (12.2.1) with KiCAD 7.0 seems to do the trick.

**Comment by Bouni** [comment]
So I fear I have to introduce another set of checks for inconsistency between OSes / wx versions etc. This is such a pain in the rear, you cannot imaging how frustration all this is  😞

**Comment by Bouni** [comment]
@hansfbaier Could you please test if this PR breaks the plugin for you?
@ OSx users could somebody of you also verify that this allow the plugin to work on OSx?

**Comment by hansfbaier** [comment]
@Bouni Yes, ` self.app = wx.PySimpleApp()` works with KiCAD 6.0 / Linux
