### ISSUE TITLE
Some parts are missing from "Search" window

### ISSUE THREAD

**Issue by makkarpov** [Bouni/kicad-jlcpcb-tools#311]
**Describe the bug**

Some parts are missing in search window, with specific examples being C5121168 and C2907412. Re-downloading the database does not solve this issue.

**To Reproduce**
1. Refresh the database.
2. Try to search C5121168 in the application.
3. Try to search C5121168 on the JLCPCB website.
4. Application find nothing, but part is present on the website.
5. Such parts are also missing "Type" and "Stock" fields in the overview table.

<details><summary>Screenshots</summary>
<p>
![image](https://github.com/Bouni/kicad-jlcpcb-tools/assets/1329592/bc2e0599-6749-4833-8bed-c43bc20c3eee)
![image](https://github.com/Bouni/kicad-jlcpcb-tools/assets/1329592/d2505104-1b59-4b67-a493-f37f80d2cdc7)
</p>
</details> 

**Expected behavior**
Application should see same set of parts as the website does.

# KiCad Version
```
Application: Редактор схем KiCad

Version: 6.0.10-2.fc37, release build

Libraries:
	wxWidgets 3.2.1
	libcurl/7.85.0 OpenSSL/3.0.5 zlib/1.2.12 brotli/1.0.9 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.51.0

Platform: Linux 6.1.8-200.fc37.x86_64 x86_64, 64 bit, Little endian, wxGTK, gnome-xorg, x11

Build Info:
	Date: Jan 14 2023 00:00:00
	wxWidgets: 3.2.1 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.78.0
	OCC: 7.6.3
	Curl: 7.85.0
	ngspice: 38
	Compiler: GCC 12.2.1 with C++ ABI 1017

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by Bouni** [comment]
Try the latest release! This got fixed by PR #310
