### ISSUE TITLE
KiCad v7

### ISSUE THREAD

**Issue by jmnc2** [Bouni/kicad-jlcpcb-tools#323]
Be nice if the readme was a bit clearer on v7 support and if it is still v6 only the state of v7 support.

The Readme has a button for KiCad v7 and v7.99 but lower down it says only supports V6 so just wondering if it supports v7?

**Comment by Bouni** [comment]
Fair enough! At the moment it supports V6, V7 and V7.99 but I think I'll drop V6 support soon

**Comment by Bouni** [comment]
I adjusted the README slightly to avoid confusion.
