### ISSUE TITLE
Update library download error

### ISSUE THREAD

**Issue by LyngaaMarineKEM** [Bouni/kicad-jlcpcb-tools#324]
**Describe the bug**
When I click Update Library button in the plugin, I get an error message:
![billede](https://github.com/Bouni/kicad-jlcpcb-tools/assets/133217601/9d27ddcc-0494-4f4b-8556-4d334a817497)

**To Reproduce**
1. Open the plugin
2. Click on Update Plugin
3. Error message appears

**Expected behavior**
JLCPCB stock file is downloaded.

# KiCad Version
Windows - KiCAD 6.0.11

**Comment by Bouni** [comment]
Update your plugin version, since 2023.05.01 the parts db is generated differently!
