### ISSUE TITLE
Support for 8 Layer PCB

### ISSUE THREAD

**Issue by lydasia** [Bouni/kicad-jlcpcb-tools#325]
Since JLCPCB global site now supports the production of 8-layer pcb, JLC (China) even supports 20-layer pcb.

**Comment by Bouni** [comment]
That should be fairly easy to achieve! Will implement that today I guess

**Comment by Bouni** [comment]
@lydasia Would you please help out and test the changes before I merge them?

**Comment by lydasia** [comment]
> @lydasia Would you please help out and test the changes before I merge them?

Hi, I've tested with an 8-layer project and a 12-layer project and didn't seen anything wrong.
![image](https://github.com/Bouni/kicad-jlcpcb-tools/assets/22676960/4d119b2b-fc0a-4567-a99e-729e96d0caea)

**Comment by Bouni** [comment]
Perfect, thanks for you help!
