### ISSUE TITLE
The tool keeps removing lcsc numbers from certain parts in my project

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [Bouni/kicad-jlcpcb-tools#352]
The jlcpcb tool keeps replacing the Cnnnnnnn numbers of capacitors with their symbol names C1, C2, C3, ....

If I update those numbers back to jlc, close kicad, reopen it, its back to C1, C2, C3 again. All other parts work fine.

![image](https://github.com/Bouni/kicad-jlcpcb-tools/assets/10342708/dc765749-7695-4405-9ebe-a4d3dc370ccb)

Using latest released kicad jlcpcb tools from your repository,

kicad is built from latest git sources on archlinux.

I am expecting that the tool also keeps the Cnnnnnnnnn jlcpart numbers for capacitors too, not only inductors and switches or ICs.

**Comment by 0xFEEDC0DE64** [comment]
the kicad project I am working at the moment is available on github:

https://github.com/0xFEEDC0DE64/esp-midi-board/tree/main/esp32_midi

**Comment by Bouni** [comment]
You're right, I see that too. Maybe the same problem that causes #351

**Comment by Bouni** [comment]
@0xFEEDC0DE64 What does the logging window print for lets say capacitor C1?

**Comment by Bouni** [comment]
This should be fixed with #356
