### ISSUE TITLE
Light icons in Dark mode

### ISSUE THREAD

**Issue by Bouni** [Bouni/kicad-jlcpcb-tools#358]
Some OS support dark mode, Windows 11 seems to do not 🫤

So I had to revert #353 

@serpent213 Would you mind submitting a new PR and check if using `.IsUsingDarkBackground()` instead of `.IsDark()` is working for you as well?

For me it works ob Windows 11

 `.IsDark()`  returns `True` and  `.IsUsingDarkBackground()`  returns `False`

![grafik](https://github.com/Bouni/kicad-jlcpcb-tools/assets/948965/b256a671-00c8-42e1-8ab7-52833293b7cd)

**Comment by serpent213** [comment]
> `.IsDark()` returns `True` and `.IsUsingDarkBackground()` returns `False`

Software development is fun, isn't it?  😉

`.IsUsingDarkBackground()` works for me. Opened #359.

**Comment by Bouni** [comment]
> Software development is fun, isn't it? 😉

Especially software that involves wx 😅
