### ISSUE TITLE
Support gerber export for 1, 2, 4 or 6 Layers (today it is limited to 2 Layers)

### ISSUE THREAD

**Issue by bvernoux** [Bouni/kicad-jlcpcb-tools#4]
Today actual plugin export Gerber with 2 Layers.
It will be great to also support in addition 1, 4 and 6 layers as so far JLCPCB support only 1, 2, 4 or 6 layers.

**Comment by Bouni** [comment]
Indeed I ignored that fact, but when I started I wasn't even sure if I get this to work for double layer PCBs at all.
I guess I will add this feature soon!

**Comment by Bouni** [comment]
@bvernoux 
I added multi layer support, if the selection is set to Auto, the plugin detects the layer count automatically, so the board setup is used. But you can still override that with the selection because KiCAD does not let you setup a single layer board as fasr as I can tell.

**Comment by bvernoux** [comment]
Yes I will do some test on different design 2, 4 and 6 layers and I will provide feedback next week
