### ISSUE TITLE
TypeError: 'FOOTPRINT' object is not iterable

### ISSUE THREAD

**Issue by Bouni** [Bouni/kicad-jlcpcb-tools#406]
@chmorgan I just realized your PR #398 breaks the plugin!

No CPL or BOM is generated and the console shows `TypeError: 'FOOTPRINT' object is not iterable`.

Thats because you replaced the helper function with `for fp in board.FindFootprintByReference(part[0]):` [here](https://github.com/Bouni/kicad-jlcpcb-tools/commit/f4db16c9410ba0e1576151bab6972623de53830f#diff-5a1a96bae787312ee9395f542c62df3cc1e00f5d44c793c2709196cbb9b97e4aR274)
This does return a single FOOTPRINT instead of a list of FOOTPRINT.
I do not remember why the helper returned a list to be honest but I also wonder why this worked for you in the first place!?

**Comment by chmorgan** [comment]
Doh. Does this occur when generating? I don’t think I’ve generated since
the change was made. Sorry about breaking that.
