### ISSUE TITLE
Assigns JLCPCB part numbers to handsoldered components

### ISSUE THREAD

**Issue by Pancra85** [Bouni/kicad-jlcpcb-tools#441]
Great plugin!!

My main problem is that it automatically assigns SMD codes to parts that are not SMD.
I am doing a board that has some SMD resistors and caps, as well as THT that I want to solder myself (for debugging,etc)
![Untitled](https://github.com/Bouni/kicad-jlcpcb-tools/assets/137118865/6e636f55-6c52-4f0e-bb7d-a6d6da3519a5)
(see the resistor selected on the list)

Maybe it should assign only on SMD footprints?

Also after I delete them and click on SAVE MAPPINGS, it doesn't get saved when I run the plugin again.

Thanks!

**Comment by Bouni** [comment]
Did you assign the LCSC number for R115 in the schematic?
You can use the Remove LCSC number button to delete the assignment:

![grafik](https://github.com/Bouni/kicad-jlcpcb-tools/assets/948965/8970f60e-ae27-4844-b921-e2d6f0715457)

Make sure to save the PCB after closing the plugin.

If you don't want a part to be assembled by JLC, use the toggle BOM/POS button. That excludes the part from the BOM as well as the POS file.

![grafik](https://github.com/Bouni/kicad-jlcpcb-tools/assets/948965/ab30c64c-012a-430b-8452-7393e3013afa)

**Comment by Pancra85** [comment]
This is what I'm doing right now:
Run the plugin
R115 has a LCSC number assigned on the list, but NOT IN THE SCHEMATIC.
I remove LCSC number and close the plugin
Save PCB
Close PCB, reopen it.
Run plugin and R115 still has a LCSC number assigned

**Comment by Pancra85** [comment]
Oh ok, it disappeared now. I guess you need to close and reopen KiCad or the file.
Thanks
