### ISSUE TITLE
Unable to download database, CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Taylor-Scion** [Bouni/kicad-jlcpcb-tools#460]
**Describe the bug**
SSL: CERTIFICATE_VERIFY_FAILED error when trying to download the jlcpcb database, fresh install so I don't have any previous versions of the database loaded.

**To Reproduce**
1. Open Plugin
2. Click download
![kicad_jlcpcb](https://github.com/Bouni/kicad-jlcpcb-tools/assets/98436529/ee23a5a3-e819-4fb2-8cff-e80892799f5a)

**Expected behavior**

# KiCad Version

```
Application: KiCad PCB Editor x64 on x64

Version: 8.0.2, release build

Libraries:
	wxWidgets 3.2.4
	FreeType 2.12.1
	HarfBuzz 8.3.0
	FontConfig 2.14.2
	libcurl/8.5.0-DEV Schannel zlib/1.3

Platform: Windows 10 (build 19044), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Apr 27 2024 23:05:17
	wxWidgets: 3.2.4 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.7.1
	Curl: 8.5.0-DEV
	ngspice: 42
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:

```

**Comment by Bouni** [comment]
I cannot reproduce this, neithor on Windows nor on Linux. Most likely not caused by the plugin. Re-open if the issue still exists
