### ISSUE TITLE
Text clipping rightside buttons

### ISSUE THREAD

**Issue by DomoticX** [Bouni/kicad-jlcpcb-tools#479]
Not a true bug (it is workable), hopefully a simple UI fix can make this better someday.....just to mention it...

```
Application: KiCad PCB Editor x64 on x64

Version: 8.0.2, release build

Libraries:
	wxWidgets 3.2.4
	FreeType 2.12.1
	HarfBuzz 8.3.0
	FontConfig 2.14.2
	libcurl/8.5.0-DEV Schannel zlib/1.3

Platform: Windows 11 (build 22631), 64-bit editie, 64 bit, Little endian, wxMSW

Build Info:
	Date: Apr 27 2024 23:05:17
	wxWidgets: 3.2.4 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.7.1
	Curl: 8.5.0-DEV
	ngspice: 42
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:
```

<img width="264" alt="image" src="https://github.com/Bouni/kicad-jlcpcb-tools/assets/8792334/fe18e3c2-fa6c-4d94-b5e5-98b9f8e032bc">

**Comment by BA7LYA** [comment]
Same.

**Comment by Bouni** [comment]
Do you guys use some sort of High res screens with DPI other than 100%

**Comment by DomoticX** [comment]
> Do you guys use some sort of High res screens with DPI other than 100%

Yes, a 4K screen with 150% zoom (windows default for 4K screens)

<img width="822" alt="image" src="https://github.com/Bouni/kicad-jlcpcb-tools/assets/8792334/cd14b0b6-0624-45ed-b8af-8d4428c4da6d">
