### ISSUE TITLE
BOM is written CPL content instead of BOM on 2024.06.02

### ISSUE THREAD

**Issue by cr1tbit** [Bouni/kicad-jlcpcb-tools#481]
Hi @Bouni 

You should probably revert this ASAP because it already propagated to the kicad repository.

https://github.com/Bouni/kicad-jlcpcb-tools/blob/5d497a5228437b4b703a32e1a89ba2de8f1dc3a0/fabrication.py#L294C1-L294C62

It probably wasn't intended, but if it was, jlc seems not to accept this format of BOM.

![image](https://github.com/Bouni/kicad-jlcpcb-tools/assets/11610199/bdc09e94-6be3-4104-8076-4c2fb7953c9f)

Best regards

**Comment by cr1tbit** [comment]
I confirmed, [2024.06.01] works ok

**Comment by Bouni** [comment]
Oh snap. I'll fix it later today 

Thanks for pointing this out.

Maybe a good time to add unit tests, just have to figure out how to do that properly

**Comment by mikesmitty** [comment]
@Bouni it looks like just the Comment and Designator column headers are swapped in the BOM output, I've been swapping the header manually before uploading it and the site processes it correctly

**Comment by Adesin-fr** [comment]
> @Bouni it looks like just the Comment and Designator column headers are swapped in the BOM output, I've been swapping the header manually before uploading it and the site processes it correctly

Same here ;) 
File is not recognized at JLCPCB !

**Comment by Bouni** [comment]
Please test the latest release, the issue should be fixed now
