### ISSUE TITLE
Generate production files using CLI

### ISSUE THREAD

**Issue by avsaase** [Bouni/kicad-jlcpcb-tools#533]
**Is your feature request related to a problem? Please describe.**
I want to generate production files in a GitHub Action by invoking a CLI instead of generating them from the GUI.

**Describe the solution you'd like**
Is there a way to generate the production files using a CLI? The workflow I would like to have is where you assign the parts from the GUI and commit the SQLite database. A GitHub Action then generates the production files and creates a release. This way only source files are committed to git.

**Describe alternatives you've considered**
Kicad provides a CLI that can generate production files but as far as I can see this does doesn't work together with the plugin.

**Comment by Bouni** [comment]
I recommend you use KiBot as it specifically made for that use case: https://kibot.readthedocs.io/en/master/

This plugin was never meant to be used headless so I never seperated the buissness logic from the GUI in away that I can easily allow headless usage ...
