### ISSUE TITLE
Part selector window does not open

### ISSUE THREAD

**Issue by Bouni** [Bouni/kicad-jlcpcb-tools#537]
Raises a `ValueError: invalid literal for int() with base 10: ''`

**Comment by dartrax** [comment]
I'm facing the same issue, running version 2025.04.02

It worked before and suddenly stopped.

<img width="413" height="718" alt="Image" src="https://github.com/user-attachments/assets/afc5b78d-0aa6-4af3-89bf-6a23bc838efc" />
