### ISSUE TITLE
Generate button not working

### ISSUE THREAD

**Issue by TristanDebrunner** [Bouni/kicad-jlcpcb-tools#549]
**Describe the bug**
Clicking the `Generate` button causes the click animation, but otherwise gets no response, and no files are generated.

# KiCad Version

```
Application: KiCad PCB Editor arm64 on arm64

Version: 8.0.5, release build

Libraries:
	wxWidgets 3.2.5
	FreeType 2.13.2
	HarfBuzz 8.3.0
	FontConfig 2.15.0
	libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.61.0

Platform: macOS Sonoma Version 14.6.1 (Build 23G93), 64 bit, Little endian, wxMac
OpenGL: Apple, Apple M1 Max, 2.1 Metal - 88.1

Build Info:
	Date: Sep  6 2024 18:52:31
	wxWidgets: 3.2.5 (wchar_t,wx containers)
	Boost: 1.84.0
	OCC: 7.7.2
	Curl: 7.87.0
	ngspice: 42
	Compiler: Clang 14.0.3 with C++ ABI 1002

Build settings:

```

**Comment by chibiconsulting** [comment]
I suspect this is related. On my system, the dialog opens and shows parts, but does not generate an upload to JLC PCB. previous versions worked fine.

Application: KiCad x86_64 on x86_64
Version: 8.0.6-unknown-202410170104~45559cb809~ubuntu24.04.1, release build
Libraries:
    wxWidgets 3.2.4
    FreeType 2.13.2
    HarfBuzz 8.3.0
    FontConfig 2.15.0
    libcurl/8.5.0 OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 (+libidn2/2.3.7) libssh/0.10.6/openssl/zlib nghttp2/1.59.0 librtmp/2.3 OpenLDAP/2.6.7
Platform: Ubuntu 24.04.1 LTS, 64 bit, Little endian, wxGTK, X11, mate, x11
OpenGL: Intel, Mesa Intel(R) HD Graphics 620 (KBL GT2), 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.2
Build Info:
    Date: Oct 17 2024 01:04:54
    wxWidgets: 3.2.4 (wchar_t,wx containers) GTK+ 3.24
    Boost: 1.83.0
    OCC: 7.6.3
    Curl: 8.5.0
    ngspice: 43
    Compiler: GCC 13.2.0 with C++ ABI 1018
Build settings:

**Comment by Bouni** [comment]
Please start the KiCAD Console before the plugin and try to generate again.

![grafik](https://github.com/user-attachments/assets/ed7774c9-3067-4d90-ad7b-631f637003d2)

The check the output in the Console, that might help figuring out what goes wrong

**Comment by leevawns** [comment]
![image](https://github.com/user-attachments/assets/91c7658b-cbb7-4492-a4cf-51c6e920fab5)

**Comment by leevawns** [comment]
![image](https://github.com/user-attachments/assets/be6de1b7-a698-4503-b94b-15d605e12c85)
