### ISSUE TITLE
JLC API integration

### ISSUE THREAD

**Issue by Bouni** [Bouni/kicad-jlcpcb-tools#55]
As @arturo182 mentioned (https://github.com/Bouni/kicad-jlcpcb-tools/issues/54#issuecomment-951891501) JLCPCB offers an API but not publicly.
I've wrote them an email with the request to access theit API.

Not sure if they agree but we'll see 🤞🏽

**Comment by Bouni** [comment]
So far not even an answer from JLCPCB 😞

**Comment by bvernoux** [comment]
> So far not even an answer from JLCPCB 😞

You should maybe open an issue directly at JLPCB they always reply very quickly usually (for standard issue) ?
Do you need help I can ask on my side ?

**Comment by Bouni** [comment]
Do you have a link where I could file such a request?
If you want to take care of that I would appreciate that for sure ☺️

**Comment by bvernoux** [comment]
You shall just log in https://jlcpcb.com then click on Chat with JLCPCB and explain them your issue that you want JLC API
If you have any issue tell me it and I will try on my side

**Comment by Bouni** [comment]
I just had a chat like you suggested (with an actual human, not an AI as I expected 🤯 ) and the supporter said he wil take care of the case and reach out to me soon.
Awesome service from JLC PCB, I'm stunned 😍

**Comment by Bouni** [comment]
So it seems that JLC staff is often promising to contact but actually never do 😒 
I'm herby revoke my statement about their great service 🤪

**Comment by Bouni** [comment]
I was in touch with JLCPCB via Twitter private messages after I've [posted this](https://twitter.com/bouni2016/status/1473570221294239746). After Christmas I should get a reply on this topic 🥳

**Comment by Bouni** [comment]
I finally got an email from JLCPCB!

But, they declined my request beacuse they want the APIs eclusively for EasyEDA (at least for now as they told me).

Sad but thats how it is ....
