### ISSUE TITLE
Calculated price is not correct

### ISSUE THREAD

**Issue by Bouni** [Bouni/kicad-jlcpcb-tools#62]
At the moment we calculate the component costs by multiplying the partcount x part price and even take price graduation into account.
But if you upload the BOM / CPL you will get a completely different price.
This is caused by the JLCPCB pricing where you have to buy a minimum number of a cirtain component.

For example you have a PCB with just 1 LED on it, a 0603. We select the LCSC number C2286 which has a cost of $0.007384615 per piece for 1 up to 199 pieces according to the CSV file.

The website already shows a slightly different price:

![image](https://user-images.githubusercontent.com/948965/139048064-69cc4ecf-d011-450e-bca8-32cff3e65f93.png)

You would think ok, $0.007384615 x 5 = $0.036923075 so approximately $0.04
If you uplad the Gerbers + BOM + CPL the website tells you 

"*For qty≤20,charges a fixed fee $0.1520*"

This important piece of information however is not included in the CSV 😕 

So all the calculated prices are wrong until we somehow can optain this information for the calculation.

**Comment by Bouni** [comment]
I implemented the use of the API and it works but does not line up with what JLC's Website calculates for some reason:

Dummy PCB, 1 LED (C2286), 40 Resistors (C25804)

![image](https://user-images.githubusercontent.com/948965/140023008-b4613a0d-9fae-4988-bc79-9bacf57adb98.png)


The leastnumber for both is 20 so the led gets the leastprice of 0.152, the resistors the regular price of 0.0025
5 Assembled PCBs should calculate like this:
`1x 0.152 + 40x 0.0025 = 0.152 + 0.1 = 0.252 x 5 = 1.26` 

![image](https://user-images.githubusercontent.com/948965/140022950-28936c96-f62e-49fc-ae88-c6349e982e1e.png)

But JLC's Website gives me totally wrong number for the parts count and a much lower parts cost for some unknown reason:

![image](https://user-images.githubusercontent.com/948965/140023117-ac2b6e92-0651-466a-983c-d2c00c3512ad.png)

20x LED seems ok, because thats the least number and the price of 0.152 fits also
206x Resistor does not fit at all, we have just 200 Resistors, but their price for the 206 fits with 0.5150

**Comment by Bouni** [comment]
Oh man, it just made click!

I cannot simply multiply the price for one pcb by 5 because the `leastnumber` for the led is 20 which is < the led count on 5 PCBs so we get the `leastprice` just once and not 5 times 🤦🏽‍♂️ 

What do you guys mean, should we always calculate the price for 5 assembled pcbs to get a correct sum?

**Comment by Bouni** [comment]
We could also calculate the cost for the SMT assembly:

![image](https://user-images.githubusercontent.com/948965/140024685-861f7cff-abd9-4eb9-9898-5bb783822059.png)

The number of solder joints is available from the database 😀

**Comment by arturo182** [comment]
It makes sense to calculate for the 5PCBs since you can't order fewer, but then you can also present that number divided by 5 to show how much it's per board.

**Comment by Bouni** [comment]
@arturo182 Indeed, that sound right!

I've implemented the `solderjoint x partcount x 0.0015 x 5` calculation as well, but again, I get a different result that is correct in my eyes 😕 

![image](https://user-images.githubusercontent.com/948965/140098132-09743b9c-8e18-4f23-872d-88da721fcc2e.png)

LED: `2 x 1 x 0.0015 = 0.003 x 5 = 0.015`
Resistors: `2 x 40 x 0.0015 = 0.12 x 5 = 0.60`

I guess the calculate the assembly fee even if the parts are not populated.
20 LEDs are charged, but just 5 are really mounted, so I guess thats where the difference comes from ...

**Comment by arturo182** [comment]
Ouch, so you're paying them for throwing out the extra LEDs :sweat_smile:

**Comment by Bouni** [comment]
I'll close this for now as its unrealistic to get this right without proper API access.
