### ISSUE TITLE
Add option to include non-selected components in BOM

### ISSUE THREAD

**Issue by t123yh** [Bouni/kicad-jlcpcb-tools#65]
Currently, all components have to be selected in order to be included in BOM. However, most resistors and capacitors can be automatically matched in JLC, making it unnecessary (and painful) to select them manually. (The slow, laggy UI adds extra pain in the ass if there are 30's individual values of resistors: every select makes the UI freeze for 3 seconds)

**Comment by Bouni** [comment]
I think instead of managing a list of non-lcsc parts we should use the include in BOM function here and include all parts that are not marked as exclude from BOM and ignore their lcsc property!?

**Comment by t123yh** [comment]
> I think instead of managing a list of non-lcsc parts we should use the include in BOM function here and include all parts that are not marked as exclude from BOM and ignore their lcsc property!?

Yes, I think you are right.
