### ISSUE TITLE
Incorrect spreadsheet formatting

### ISSUE THREAD

**Issue by ojthetiny** [Bouni/kicad-jlcpcb-tools#77]
Both Bom and CPL files are compressed into a single column with all the information, makes this impossible to use

![image](https://user-images.githubusercontent.com/65928618/142776293-598b20dc-c1e5-4a59-93c4-5461c1deb1a8.png)

**Comment by ojthetiny** [comment]
Disregard. Double checked some settings and it's fine

**Comment by arturo182** [comment]
For future people: Make sure to tell the spreadsheet software to use "," as a delimiter when opening the BOM :)
