### ISSUE TITLE
Download of the CSV failed, no existing library found, exit plugin now

### ISSUE THREAD

**Issue by katodo** [Bouni/kicad-jlcpcb-tools#78]
I just installed this plugin but I've this error on opening:
"Download of the CSV failed, no existing library found, exit plugin now"

![image](https://user-images.githubusercontent.com/6282985/144559909-dfd57e98-478e-4e5d-8f22-986f98a9452a.png)

am I forgetting some initial steps?

**Comment by Bouni** [comment]
This is because JLCPCB from time to time fails at serving there parts database CSV.
Try it later, maybe they have fixed it then.

I guess I have to setup my own caching server to avoid this problem bin the future 😑

**Comment by pixsysedp** [comment]
I'm testing now from another network on a windows pc but there are same problem... can you exchange CSV here?

**Comment by Bouni** [comment]
Unfortunately not at the moment.
The JLCPCB link gives a 404 😕

**Comment by obra** [comment]
Would it make sense to seed the parts database with an ancient copy in git? Alternatively, is it possible to make the fabrication outputs functionality not depend on the download?

**Comment by AiGreek** [comment]
Same error for me. LCSC seems to be unavailable. If it can help i uploaded  the two files needed to use the plugin.


**_KiCad\6.0\scripting\plugins\JLCPCB_**
```
https://www.dropbox.com/s/l68gpu5s434zrcj/jlcpcb_parts.db?dl=0
https://www.dropbox.com/s/vqfrrwnyccee2ea/parts.db?dl=0
```

**Comment by Bouni** [comment]
> Would it make sense to seed the parts database with an ancient copy in git? Alternatively, is it possible to make the fabrication outputs functionality not depend on the download?

I think caching the CSV is the better option.
The generation without the possibility to select and assign LCSC part numbers seems kind of useless to me, why would you do that?

**Comment by Bouni** [comment]
> Same error for me. LCSC seems to be unavailable. If it can help i uploaded  the two files needed to use the plugin.
> 
> 
> **_KiCad\6.0\scripting\plugins\kicad-jlcpcb-tools\jlcpcb_**
> ```
> https://www.dropbox.com/s/l68gpu5s434zrcj/jlcpcb_parts.db?dl=0
> https://www.dropbox.com/s/vqfrrwnyccee2ea/parts.db?dl=0
> ```

The parts.db is not needed, it's project specific!

**Comment by AiGreek** [comment]
woops my bad ^^'

**Comment by obra** [comment]
In this case, I already have manually assigned LCSC parts on most of my BOM.  But also, their web based part assignment doesn’t suck.

**Comment by Bouni** [comment]
> In this case, I already have manually assigned LCSC parts on most of my BOM.  But also, their web based part assignment doesn’t suck. 

Ok, I've not seen that aspect so far.
I'll look into it next week after my vacation

**Comment by obra** [comment]
Have a great vacation!

**Comment by Bouni** [comment]
I totally forgot that this is the default behaviour in the now merged `major-refactor` branch.
You get an error but still can generate the files
