### ISSUE TITLE
Failed to download CSV

### ISSUE THREAD

**Issue by Polsaker** [Bouni/kicad-jlcpcb-tools#89]
Hello, I just installed the plugin (from your PCM repo), fired it up and this error pops up:

![image](https://user-images.githubusercontent.com/2000719/146694223-dc8594f6-63d2-4526-bd9a-ad676a37e673.png)

**Comment by Bouni** [comment]
@Polsaker Thats new, in the past JLC just randomly returned a 404 when users tried to download the CSV, nw they seem to actively block the use by tools like this here. 
Adding a browser user-agent header seems to solve this for the moment.
Lets hope they don't add additional measures to prevent this 😬
