### ISSUE TITLE
Library "Package" search filter shouldn't be exact

### ISSUE THREAD

**Issue by riskable** [Bouni/kicad-jlcpcb-tools#92]
Searching for "SOT-23" in the Package field only shows parts that have that exact package name when it should show parts with "SOT-23-3", "SOT-23-4", "SOT-23-5", etc.

![Screenshot_20211222_133750](https://user-images.githubusercontent.com/66987/147140138-d09c9fc3-802a-4fe5-9077-d440e6553720.png)

IMHO the search filter should be partial match by default with maybe the option to use quotes for an exact match.

**Comment by riskable** [comment]
I just realized: This might have nothing to do with your code but might be a limitation of the JLCPCB API. If that's the case you can just close this since there's nothing you can do about it :shrug:

**Comment by Bouni** [comment]
You can use `%` as wildcard operator to find packages that contain that string. For example `SOT-23%` will match `SOT-23` as well as `SOT-23-5`.
Click on the help button, there is a description!

![image](https://user-images.githubusercontent.com/948965/147247670-6e64a0a0-9350-4050-bf7f-1b8a593fbd36.png)
