### ISSUE TITLE
Parts not being put into `part_info` database

### ISSUE THREAD

**Issue by OnesAndZer0s** [Bouni/kicad-jlcpcb-tools#95]
I'm running linux mint, downloaded plugin, ran plugin, no dice.

The `parts` and `meta` database has entries, however. But, the `rotation`, and `part_info` databases are not.

https://user-images.githubusercontent.com/37850372/147495010-612060b2-23f7-44bd-a0d4-7fdc24ed5b82.mov
I've added some debug entries in the logger. Currently still digging through the source to see why this is happening

Edit : So, I'm an idiot and didn't hit the `Manage Rotation` button, causing the `rotation` database to update. The `part_info` database is still empty though

**Comment by Bouni** [comment]
The rotations db is empty by default, by clicking Manage rotations -> Update the rotations CSV is downloaded from Github and imported into the database.

The `part_info` table in the `project.db` is normally populated once you open the plugin, it reads the `.kicad_pcb` file via the API and puts all parts into it.

You should see output like this in the bottom logger:

![image](https://user-images.githubusercontent.com/948965/147537149-e0a817a7-4430-4d75-8079-0098d956a10b.png)

**Comment by Bouni** [comment]
@OnesAndZer0s Any news on this?

**Comment by OnesAndZer0s** [comment]
It works fine, I'm just a mega idiot. I was under the impression that you searched a part from the database and then put it on the sketch, not the other way around. Probably should specify that in the "how to use"

**Comment by Bouni** [comment]
No problem, happy that it works now!

> Probably should specify that in the "how to use"

Yes, documentation need improvement 😅
