### ISSUE TITLE
grouped components ? 

### ISSUE THREAD

**Issue by AiGreek** [Bouni/kicad-jlcpcb-tools#97]
yeah, it's me, again :D 
I'm making a HUGE pcb with a lot of LED, header, same resistors, capacitors, etc ... and i was wonrdering if it's possible to group components by value to add LCSC reference once without having to scroll for 10 years each time..

This what we have : 
![image](https://user-images.githubusercontent.com/16197044/147830798-b48040c2-26f3-4ae3-b550-73e1a78a33f2.png)

This is what we COULD have : 
![image](https://user-images.githubusercontent.com/16197044/147830947-2c80d60c-adea-4c07-b026-6c73bd1216ed.png)

Not sure if it's easy to do, or even if it's useful for anyone except me but meh... why not ?!

**Comment by Bouni** [comment]
The `Select alike` button is your friend 😉

**Comment by arturo182** [comment]
Maybe "Select similar" would've been more intuitive 🤔

**Comment by Bouni** [comment]
Naming was suggested by a native speaker (at least I guess he is) 🤷

**Comment by AiGreek** [comment]
> The `Select alike` button is your friend 😉

I think I misunderstood myself. It is not a question of component selections, but of display of components in the window. I know this button exists (and indeed, the English translation is weird) ^^

**Comment by Bouni** [comment]
I have to look into that but I guess that's rather hard to implement. WX lists are a pain in the rear if you use them normally, so having this type of ui sugar is extremely difficult.

**Comment by Bouni** [comment]
I think I'll not implement ths for now as the `select alike` button is good enough in my opinion. I think I'll go for @arturo182's suggestion and change the button label from `select alike` to `select similar`
